#!/usr/bin/env python3
# -*- coding: utf-8 -*-

"""
finetune_cnn.py

Frame-level jersey-number recognition with a CNN backbone + digit-wise heads:
  - num_digits head: 3 classes (UNK=0, 1, 2)
  - tens head:      12 classes (0-9, BLANK=10(for one-digit), UNK=11)
  - ones head:      11 classes (0-9, UNK=10)

Training uses frame-level supervision from split CSVs.

Compatible with TWO CSV formats:

(1) Old (preprocessed) format:
  image_path, jersey_number, num_digits, tens, ones, tracklet_id

(2) Current (digits-only) format:
  image_path, label
  - label is jersey_number (>=0)
  - tracklet_id is derived from the parent directory name of image_path
  - num_digits/tens/ones are derived from jersey_number

Test-time prediction aggregates per-frame decoded jersey numbers with confidence-weighted voting,
writing OUT_PRED_JSON = {tracklet_id: jersey_number_pred}.

Robustness:
- Corrupt/unreadable images are skipped (train dataset + test inference).
"""

import os
import csv
import random
import json
from dataclasses import dataclass
from typing import List, Dict, Tuple, Optional

from PIL import Image, ImageFile, UnidentifiedImageError
from tqdm import tqdm

import torch
import torch.nn as nn
import torch.nn.functional as F
from torch.utils.data import Dataset, DataLoader
from torchvision import transforms, models

import matplotlib
matplotlib.use("Agg")  # no display
import matplotlib.pyplot as plt

# PIL robustness knobs
ImageFile.LOAD_TRUNCATED_IMAGES = True  # helps with some truncated JPGs


# =======================
# HARD-CODED PATHS  (KEEP THESE EXACTLY)
# =======================
# CHANGED: point to digits-only CSVs (exclude -1) generated by make_digits_csv.py
SPLIT_DIR = "/scratch/st-li1210-1/yijun/519Project/jersey-number-pipeline/proposed_pipeline/splits_digits"
TRAIN_CSV = os.path.join(SPLIT_DIR, "train_digits.csv")
VAL_CSV   = os.path.join(SPLIT_DIR, "val_digits.csv")

IMAGENET_RESNET50_PTH = "/scratch/st-li1210-1/yijun/519Project/jersey-number-pipeline/proposed_pipeline/torch_weights/resnet50_imagenet.pth"

# Test images folder structure assumed:
#   .../test/images/<tracklet_id>/*.jpg
TEST_IMG_ROOT = "/scratch/st-li1210-1/yijun/519Project/jersey-number-pipeline/data/SoccerNet/jersey-2023/test/images"

OUT_DIR = "/scratch/st-li1210-1/yijun/519Project/jersey-number-pipeline/proposed_pipeline/runs_finetune_digitwise"
os.makedirs(OUT_DIR, exist_ok=True)

BEST_CKPT = os.path.join(OUT_DIR, "best.pt")
LAST_CKPT = os.path.join(OUT_DIR, "last.pt")
OUT_PRED_JSON = os.path.join(OUT_DIR, "test_pred.json")
# =======================


# =======================
# TRAINING HYPERPARAMS
# =======================
MODEL_NAME = "resnet50"     # "resnet50" or "efficientnet_b2"
IMAGE_SIZE = 224
EPOCHS = 15
BATCH_SIZE = 64
LR = 3e-4
WEIGHT_DECAY = 1e-4
DROPOUT = 0.2
LABEL_SMOOTHING = 0.1
NUM_WORKERS = 4
SEED = 42
USE_AMP = True

# Optional confidence gating at inference:
# if confidence too low -> output -1
FRAME_CONF_THRESH: Optional[float] = None  # e.g. 0.55
# =======================


# =======================
# LABEL CONVENTIONS (must match preprocess_index.py)
# =======================
ONES_UNK = 10            # ones: 0..9 + UNK(10)  => 11 classes
TENS_BLANK = 10          # tens: 0..9 + BLANK(10) + UNK(11) => 12 classes
TENS_UNK = 11
NUM_UNK = 0              # num_digits: UNK(0), 1, 2 => 3 classes
# =======================


@dataclass(frozen=True)
class Sample:
    image_path: str
    jersey_number: int
    num_digits: int
    tens: int
    ones: int
    tracklet_id: str


def seed_all(seed: int):
    random.seed(seed)
    torch.manual_seed(seed)
    torch.cuda.manual_seed_all(seed)


def _safe_int(x: str) -> int:
    # robust parse for "7", "7.0", " 7 "
    return int(float(str(x).strip()))


def _derive_tracklet_id_from_path(image_path: str) -> str:
    # Expected: .../<split>/images/<tracklet_id>/<frame>.jpg
    # If not, fallback to immediate parent directory name
    return os.path.basename(os.path.dirname(image_path))


def _encode_jersey_to_heads(jersey_number: int) -> Tuple[int, int, int]:
    """
    Convert jersey_number -> (num_digits, tens, ones) using existing label conventions.

    jersey_number:
      -1 -> unknown
      0..9 -> 1-digit
      10..99 -> 2-digit

    Returns:
      num_digits in {NUM_UNK(0), 1, 2}
      tens in {0..9, BLANK(10), UNK(11)}
      ones in {0..9, UNK(10)}
    """
    if jersey_number == -1:
        return NUM_UNK, TENS_UNK, ONES_UNK

    if jersey_number < 0:
        # treat anything negative as unknown
        return NUM_UNK, TENS_UNK, ONES_UNK

    if jersey_number <= 9:
        return 1, TENS_BLANK, int(jersey_number)

    if jersey_number <= 99:
        t = jersey_number // 10
        o = jersey_number % 10
        return 2, int(t), int(o)

    # If your dataset can exceed 99, you need a 3-digit head design.
    # Minimal-change behavior: mark as unknown.
    return NUM_UNK, TENS_UNK, ONES_UNK


def load_split_csv(path: str) -> List[Sample]:
    """
    Supports two formats:

    (A) Old format columns:
      image_path, jersey_number, num_digits, tens, ones, tracklet_id

    (B) Current digits-only columns:
      image_path, label
      (or image_path + jersey_number)
    Derives:
      tracklet_id from parent folder
      num_digits/tens/ones from jersey_number
    """
    if not os.path.isfile(path):
        raise FileNotFoundError(f"Split CSV not found: {path}")

    out: List[Sample] = []
    with open(path, "r", newline="", encoding="utf-8") as f:
        r = csv.DictReader(f)
        if r.fieldnames is None:
            raise ValueError(f"{path} has no header")

        fields = set(r.fieldnames)

        # ---- Case A: old preprocessed format ----
        required_old = {"image_path", "jersey_number", "num_digits", "tens", "ones", "tracklet_id"}
        if required_old.issubset(fields):
            for row in r:
                out.append(Sample(
                    image_path=row["image_path"],
                    jersey_number=_safe_int(row["jersey_number"]),
                    num_digits=_safe_int(row["num_digits"]),
                    tens=_safe_int(row["tens"]),
                    ones=_safe_int(row["ones"]),
                    tracklet_id=str(row["tracklet_id"]),
                ))

        # ---- Case B: digits-only format ----
        else:
            # We require image_path and either label or jersey_number
            if "image_path" not in fields:
                raise ValueError(f"{path} must contain 'image_path'. Got {r.fieldnames}")

            label_col = None
            if "label" in fields:
                label_col = "label"
            elif "jersey_number" in fields:
                label_col = "jersey_number"
            else:
                raise ValueError(f"{path} must contain 'label' or 'jersey_number'. Got {r.fieldnames}")

            for row in r:
                image_path = row["image_path"]
                jersey_number = _safe_int(row[label_col])

                num_digits, tens, ones = _encode_jersey_to_heads(jersey_number)
                tracklet_id = row["tracklet_id"] if "tracklet_id" in fields else _derive_tracklet_id_from_path(image_path)

                out.append(Sample(
                    image_path=image_path,
                    jersey_number=jersey_number,
                    num_digits=num_digits,
                    tens=tens,
                    ones=ones,
                    tracklet_id=str(tracklet_id),
                ))

    # drop missing images
    out2 = [s for s in out if os.path.isfile(s.image_path)]
    if len(out2) != len(out):
        print(f"[WARN] Dropped {len(out)-len(out2)} missing images from {path}", flush=True)
    if not out2:
        raise ValueError(f"No valid images found in {path}")
    return out2


class JerseyFrameDataset(Dataset):
    def __init__(self, samples: List[Sample], image_size: int, train: bool):
        self.samples = samples

        if train:
            # Augmentations tuned for motion blur / occlusion
            self.tf = transforms.Compose([
                transforms.Resize((image_size, image_size)),
                transforms.RandomApply([transforms.ColorJitter(0.2, 0.2, 0.2, 0.05)], p=0.6),
                transforms.RandomGrayscale(p=0.1),
                transforms.RandomHorizontalFlip(p=0.5),
                transforms.RandomApply([transforms.GaussianBlur(kernel_size=3, sigma=(0.1, 2.0))], p=0.25),
                transforms.ToTensor(),
                transforms.RandomErasing(p=0.35, scale=(0.02, 0.2), ratio=(0.3, 3.3), value="random"),
                transforms.Normalize([0.485, 0.456, 0.406],
                                     [0.229, 0.224, 0.225]),
            ])
        else:
            self.tf = transforms.Compose([
                transforms.Resize((image_size, image_size)),
                transforms.ToTensor(),
                transforms.Normalize([0.485, 0.456, 0.406],
                                     [0.229, 0.224, 0.225]),
            ])

    def __len__(self):
        return len(self.samples)

    def __getitem__(self, idx):
        for _ in range(10):
            s = self.samples[idx]
            try:
                with Image.open(s.image_path) as im:
                    im = im.convert("RGB")
                x = self.tf(im)

                num_digits = torch.tensor(s.num_digits, dtype=torch.long)
                tens = torch.tensor(s.tens, dtype=torch.long)
                ones = torch.tensor(s.ones, dtype=torch.long)
                jersey = torch.tensor(s.jersey_number, dtype=torch.long)

                return x, num_digits, tens, ones, jersey, s.tracklet_id

            except (UnidentifiedImageError, OSError, ValueError) as e:
                print(f"[WARN] Bad image skipped: {s.image_path} ({type(e).__name__})", flush=True)
                idx = (idx + 1) % len(self.samples)

        raise RuntimeError("Too many unreadable images encountered in a row; dataset may be corrupted.")



class DigitWiseHeadNet(nn.Module):
    """
    Backbone + 3 classification heads:
      - num_digits: 3 classes
      - tens: 12 classes
      - ones: 11 classes
    """
    def __init__(self, name: str, dropout: float):
        super().__init__()
        name = name.lower()

        if name == "resnet50":
            m = models.resnet50(weights=None)
            feat_dim = m.fc.in_features
            m.fc = nn.Identity()
            self.backbone = m

        elif name == "efficientnet_b2":
            m = models.efficientnet_b2(weights=None)
            feat_dim = m.classifier[1].in_features
            m.classifier = nn.Identity()
            self.backbone = m

        else:
            raise ValueError("MODEL_NAME must be 'resnet50' or 'efficientnet_b2'")

        self.drop = nn.Dropout(dropout)
        self.head_num = nn.Linear(feat_dim, 3)    # 0,1,2
        self.head_tens = nn.Linear(feat_dim, 12)  # 0..11
        self.head_ones = nn.Linear(feat_dim, 11)  # 0..10

    def forward(self, x):
        feat = self.backbone(x)
        feat = self.drop(feat)
        return self.head_num(feat), self.head_tens(feat), self.head_ones(feat)


@torch.no_grad()
def decode_frame(num_logits: torch.Tensor,
                 tens_logits: torch.Tensor,
                 ones_logits: torch.Tensor,
                 conf_thresh: Optional[float] = None) -> Tuple[torch.Tensor, torch.Tensor]:
    """
    Decode per-frame logits -> jersey_number in {-1, 0..99}.
    Returns:
      jersey_pred: [B] long
      conf: [B] float
    """
    num_prob  = torch.softmax(num_logits, dim=1)
    tens_prob = torch.softmax(tens_logits, dim=1)
    ones_prob = torch.softmax(ones_logits, dim=1)

    num_pred  = torch.argmax(num_prob,  dim=1)
    tens_pred = torch.argmax(tens_prob, dim=1)
    ones_pred = torch.argmax(ones_prob, dim=1)

    num_conf  = torch.max(num_prob,  dim=1).values
    tens_conf = torch.max(tens_prob, dim=1).values
    ones_conf = torch.max(ones_prob, dim=1).values

    # confidence product of relevant heads
    conf = ones_conf * num_conf
    conf = torch.where(num_pred == 2, conf * tens_conf, conf)

    B = num_pred.shape[0]
    jersey = torch.full((B,), -1, dtype=torch.long, device=num_pred.device)

    # Optional confidence gating: low conf -> force unknown
    if conf_thresh is not None:
        low = conf < conf_thresh
        num_pred = num_pred.clone()
        tens_pred = tens_pred.clone()
        ones_pred = ones_pred.clone()
        num_pred[low] = NUM_UNK
        tens_pred[low] = TENS_UNK
        ones_pred[low] = ONES_UNK

    # Unknown cases => -1
    unk = (num_pred == NUM_UNK) | (ones_pred == ONES_UNK)

    # 1-digit: tens should be BLANK and ones 0..9
    one_ok = (num_pred == 1) & (~unk) & (tens_pred == TENS_BLANK) & (ones_pred <= 9)
    jersey[one_ok] = ones_pred[one_ok]

    # 2-digit: tens 0..9 and ones 0..9
    two_ok = (num_pred == 2) & (~unk) & (tens_pred <= 9) & (ones_pred <= 9)
    jersey[two_ok] = tens_pred[two_ok] * 10 + ones_pred[two_ok]

    return jersey, conf


@torch.no_grad()
def eval_frame_metrics(model: nn.Module, loader: DataLoader, device: torch.device) -> Dict[str, float]:
    model.eval()
    total = 0

    num_correct = 0
    tens_correct = 0
    ones_correct = 0
    jersey_correct = 0

    for x, num_t, tens_t, ones_t, jersey_t, _tid in loader:
        x = x.to(device, non_blocking=True)
        num_t = num_t.to(device, non_blocking=True)
        tens_t = tens_t.to(device, non_blocking=True)
        ones_t = ones_t.to(device, non_blocking=True)
        jersey_t = jersey_t.to(device, non_blocking=True)

        num_logits, tens_logits, ones_logits = model(x)

        num_pred = num_logits.argmax(dim=1)
        tens_pred = tens_logits.argmax(dim=1)
        ones_pred = ones_logits.argmax(dim=1)

        num_correct += int((num_pred == num_t).sum().item())
        tens_correct += int((tens_pred == tens_t).sum().item())
        ones_correct += int((ones_pred == ones_t).sum().item())

        jersey_pred, _ = decode_frame(num_logits, tens_logits, ones_logits, conf_thresh=None)
        jersey_correct += int((jersey_pred == jersey_t).sum().item())

        total += int(jersey_t.numel())

    return {
        "num_acc": num_correct / max(total, 1),
        "tens_acc": tens_correct / max(total, 1),
        "ones_acc": ones_correct / max(total, 1),
        "jersey_acc": jersey_correct / max(total, 1),
    }


def list_tracklets(img_root: str) -> List[str]:
    tids = []
    if not os.path.isdir(img_root):
        raise FileNotFoundError(f"TEST_IMG_ROOT not found: {img_root}")
    for d in os.listdir(img_root):
        p = os.path.join(img_root, d)
        if os.path.isdir(p):
            tids.append(d)
    return sorted(tids)


def list_images(tracklet_dir: str) -> List[str]:
    exts = (".jpg", ".jpeg", ".png")
    paths = []
    for n in os.listdir(tracklet_dir):
        if n.lower().endswith(exts):
            paths.append(os.path.join(tracklet_dir, n))
    return sorted(paths)


@torch.no_grad()
def predict_tracklet(model: nn.Module,
                     tracklet_dir: str,
                     tf,
                     device: torch.device,
                     conf_thresh: Optional[float]) -> int:
    """
    Tracklet prediction by confidence-weighted voting over decoded frame jersey numbers.
    Robust to corrupt images (skips them).
    """
    img_paths = list_images(tracklet_dir)
    if not img_paths:
        return -1

    model.eval()
    preds = []
    confs = []

    bs = 256
    for i in range(0, len(img_paths), bs):
        batch_paths = img_paths[i:i + bs]
        xs = []

        for p in batch_paths:
            try:
                with Image.open(p) as im:
                    im = im.convert("RGB")
                xs.append(tf(im))
            except (UnidentifiedImageError, OSError, ValueError) as e:
                print(f"[WARN] Bad test image skipped: {p} ({type(e).__name__})", flush=True)
                continue

        if len(xs) == 0:
            continue

        x = torch.stack(xs, dim=0).to(device)

        num_logits, tens_logits, ones_logits = model(x)
        jersey_pred, conf = decode_frame(num_logits, tens_logits, ones_logits, conf_thresh=conf_thresh)

        preds.append(jersey_pred.cpu())
        confs.append(conf.cpu())

    if len(preds) == 0:
        return -1

    preds = torch.cat(preds, dim=0)
    confs = torch.cat(confs, dim=0)

    score: Dict[int, float] = {}
    for j, c in zip(preds.tolist(), confs.tolist()):
        score[j] = score.get(j, 0.0) + float(c)

    # If -1 dominates, output -1; else output best-scored jersey
    neg1 = score.get(-1, 0.0)
    best_j, best_s = max(score.items(), key=lambda kv: kv[1])
    if best_j == -1:
        return -1
    if neg1 >= 0.9 * best_s:
        return -1
    return int(best_j)


@torch.no_grad()
def predict_test_json(model: nn.Module, device: torch.device) -> None:
    """
    Writes OUT_PRED_JSON in the same dict format as test_gt.json:
      { "tracklet_id": jersey_number, ... }
    """
    # Use eval/test transforms (no augmentation)
    tf = transforms.Compose([
        transforms.Resize((IMAGE_SIZE, IMAGE_SIZE)),
        transforms.ToTensor(),
        transforms.Normalize([0.485, 0.456, 0.406],
                             [0.229, 0.224, 0.225]),
    ])

    tids = list_tracklets(TEST_IMG_ROOT)
    out: Dict[str, int] = {}

    for tid in tqdm(tids, desc="predict test"):
        tdir = os.path.join(TEST_IMG_ROOT, tid)
        out[str(tid)] = predict_tracklet(model, tdir, tf, device, FRAME_CONF_THRESH)

    with open(OUT_PRED_JSON, "w", encoding="utf-8") as f:
        json.dump(out, f)
    print(f"[OK] wrote test predictions json -> {OUT_PRED_JSON}", flush=True)


def save_curves_png(history: List[Dict[str, float]], out_dir: str):
    """
    history: list of dicts with keys:
      epoch, train_loss, val_jersey_acc, val_num_acc, val_tens_acc, val_ones_acc
    Writes:
      curve_loss.png
      curve_val_acc.png
    """
    if not history:
        return

    epochs = [h["epoch"] for h in history]

    # Loss curve
    plt.figure()
    plt.plot(epochs, [h["train_loss"] for h in history])
    plt.xlabel("epoch")
    plt.ylabel("train loss")
    plt.title("Training Loss")
    plt.tight_layout()
    plt.savefig(os.path.join(out_dir, "curve_loss.png"), dpi=200)
    plt.close()

    # Val accuracies
    plt.figure()
    plt.plot(epochs, [h["val_jersey_acc"] for h in history], label="val jersey")
    plt.plot(epochs, [h["val_num_acc"] for h in history], label="val num")
    plt.plot(epochs, [h["val_tens_acc"] for h in history], label="val tens")
    plt.plot(epochs, [h["val_ones_acc"] for h in history], label="val ones")
    plt.xlabel("epoch")
    plt.ylabel("accuracy")
    plt.title("Validation Accuracies")
    plt.legend()
    plt.tight_layout()
    plt.savefig(os.path.join(out_dir, "curve_val_acc.png"), dpi=200)
    plt.close()


def load_resnet50_imagenet_into_backbone(model: nn.Module, weight_path: str):
    """
    Load torchvision resnet50 ImageNet weights (state_dict) into model.backbone.
    model.backbone must be a torchvision resnet50 with fc already replaced by Identity.
    """
    if not os.path.isfile(weight_path):
        raise FileNotFoundError(f"Missing pretrained weights: {weight_path}")

    state = torch.load(weight_path, map_location="cpu")

    # Some checkpoints might wrap under a key; handle both
    if isinstance(state, dict) and "state_dict" in state:
        state = state["state_dict"]

    missing, unexpected = model.backbone.load_state_dict(state, strict=False)
    # strict=False because your backbone has fc=Identity, but weights include fc.* keys.

    if missing:
        print(f"[WARN] Missing keys when loading ImageNet weights (unexpected): {missing[:5]} ...", flush=True)
    if unexpected:
        print(f"[INFO] Ignored unexpected keys (expected): {unexpected[:5]} ...", flush=True)


def main():
    seed_all(SEED)
    device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
    print("[INFO] device:", device, flush=True)

    train_samples = load_split_csv(TRAIN_CSV)
    val_samples   = load_split_csv(VAL_CSV)

    print(f"[INFO] frames train={len(train_samples)} val={len(val_samples)}", flush=True)
    print("[INFO] heads: num_digits=3 classes | tens=12 classes | ones=11 classes", flush=True)

    train_ds = JerseyFrameDataset(train_samples, IMAGE_SIZE, train=True)
    val_ds   = JerseyFrameDataset(val_samples, IMAGE_SIZE, train=False)

    train_loader = DataLoader(
        train_ds, batch_size=BATCH_SIZE, shuffle=True,
        num_workers=NUM_WORKERS, pin_memory=(device.type == "cuda"), drop_last=True
    )
    val_loader = DataLoader(
        val_ds, batch_size=BATCH_SIZE, shuffle=False,
        num_workers=NUM_WORKERS, pin_memory=(device.type == "cuda")
    )

    history: List[Dict[str, float]] = []

    model = DigitWiseHeadNet(MODEL_NAME, DROPOUT).to(device)

    if MODEL_NAME.lower() == "resnet50":
        load_resnet50_imagenet_into_backbone(model, IMAGENET_RESNET50_PTH)
    else:
        print("[WARN] Offline pretrained loading implemented only for resnet50 right now.", flush=True)

    opt = torch.optim.AdamW(model.parameters(), lr=LR, weight_decay=WEIGHT_DECAY)
    scaler = torch.cuda.amp.GradScaler() if (USE_AMP and device.type == "cuda") else None

    best = -1.0

    for ep in range(1, EPOCHS + 1):
        model.train()
        running = 0.0
        n = 0

        for x, num_t, tens_t, ones_t, _jersey_t, _tid in tqdm(train_loader, desc=f"train E{ep}", leave=False):
            x = x.to(device, non_blocking=True)
            num_t = num_t.to(device, non_blocking=True)
            tens_t = tens_t.to(device, non_blocking=True)
            ones_t = ones_t.to(device, non_blocking=True)

            opt.zero_grad(set_to_none=True)

            if scaler is not None:
                with torch.cuda.amp.autocast():
                    num_logits, tens_logits, ones_logits = model(x)
                    loss = (
                        F.cross_entropy(num_logits, num_t, label_smoothing=LABEL_SMOOTHING)
                        + F.cross_entropy(tens_logits, tens_t, label_smoothing=LABEL_SMOOTHING)
                        + F.cross_entropy(ones_logits, ones_t, label_smoothing=LABEL_SMOOTHING)
                    )
                scaler.scale(loss).backward()
                scaler.step(opt)
                scaler.update()
            else:
                num_logits, tens_logits, ones_logits = model(x)
                loss = (
                    F.cross_entropy(num_logits, num_t, label_smoothing=LABEL_SMOOTHING)
                    + F.cross_entropy(tens_logits, tens_t, label_smoothing=LABEL_SMOOTHING)
                    + F.cross_entropy(ones_logits, ones_t, label_smoothing=LABEL_SMOOTHING)
                )
                loss.backward()
                opt.step()

            running += float(loss.item()) * x.size(0)
            n += x.size(0)

        train_loss = running / max(n, 1)
        val_m = eval_frame_metrics(model, val_loader, device)

        print(
            f"[E{ep:02d}] loss={train_loss:.4f} | "
            f"val jersey_acc={val_m['jersey_acc']*100:.2f}% "
            f"(num={val_m['num_acc']*100:.2f}% tens={val_m['tens_acc']*100:.2f}% ones={val_m['ones_acc']*100:.2f}%)",
            flush=True
        )

        history.append({
            "epoch": ep,
            "train_loss": train_loss,
            "val_jersey_acc": val_m["jersey_acc"],
            "val_num_acc": val_m["num_acc"],
            "val_tens_acc": val_m["tens_acc"],
            "val_ones_acc": val_m["ones_acc"],
        })

        # Save last every epoch
        torch.save({
            "epoch": ep,
            "model": MODEL_NAME,
            "image_size": IMAGE_SIZE,
            "state_dict": model.state_dict(),
            "best_val_jersey_acc": best,
            "label_convention": {
                "num_digits": {"UNK": 0, "classes": 3},
                "tens": {"BLANK": 10, "UNK": 11, "classes": 12},
                "ones": {"UNK": 10, "classes": 11},
            },
        }, LAST_CKPT)

        # Save best by jersey frame val acc
        if val_m["jersey_acc"] > best:
            best = val_m["jersey_acc"]
            torch.save({
                "epoch": ep,
                "model": MODEL_NAME,
                "image_size": IMAGE_SIZE,
                "state_dict": model.state_dict(),
                "best_val_jersey_acc": best,
                "label_convention": {
                    "num_digits": {"UNK": 0, "classes": 3},
                    "tens": {"BLANK": 10, "UNK": 11, "classes": 12},
                    "ones": {"UNK": 10, "classes": 11},
                },
            }, BEST_CKPT)
            print(f"[SAVE] best -> {BEST_CKPT}", flush=True)

    save_curves_png(history, OUT_DIR)
    print("[OK] Saved final training curves", flush=True)

    print(f"[DONE] best val jersey frame acc: {best*100:.2f}%", flush=True)
    print(f"[DONE] best ckpt: {BEST_CKPT}", flush=True)

    # Load best and predict test JSON
    ckpt = torch.load(BEST_CKPT, map_location=device)
    model.load_state_dict(ckpt["state_dict"])
    predict_test_json(model, device)


if __name__ == "__main__":
    main()
